// Copyright 2026 The cxas-harness Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Every CES REST method, generated from the vendored discovery documents.
//!
//! Do not edit by hand: run `python tools/generate_methods.py`. The
//! `declared_table_matches_discovery_exactly` parity test fails if this file
//! and `reference/ces/` ever disagree, in either direction.
//!
//! 170 methods (v1 66, v1beta 104) at the revisions recorded in `PINNED.toml`.

use super::method::{beta, v1, MethodSpec};

/// Every method CES declares, addressable through [`super::RequestBuilder`].
///
/// Being addressable is not the same as being wrapped in a typed helper:
/// see `MODELLED` for the subset this workspace models with its own types.
pub const METHODS: &[MethodSpec] = &[
    // ---- v1 (66 methods) ----
    v1("ces.projects.locations.apps.agents.create", "POST", "v1/{+parent}/agents"),
    v1("ces.projects.locations.apps.agents.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.agents.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.agents.list", "GET", "v1/{+parent}/agents"),
    v1("ces.projects.locations.apps.agents.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.changelogs.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.changelogs.list", "GET", "v1/{+parent}/changelogs"),
    v1("ces.projects.locations.apps.conversations.batchDelete", "POST", "v1/{+parent}/conversations:batchDelete"),
    v1("ces.projects.locations.apps.conversations.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.conversations.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.conversations.list", "GET", "v1/{+parent}/conversations"),
    v1("ces.projects.locations.apps.create", "POST", "v1/{+parent}/apps"),
    v1("ces.projects.locations.apps.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.deployments.create", "POST", "v1/{+parent}/deployments"),
    v1("ces.projects.locations.apps.deployments.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.deployments.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.deployments.getExtendedAgentCard", "GET", "v1/{+tenant}/extendedAgentCard"),
    v1("ces.projects.locations.apps.deployments.list", "GET", "v1/{+parent}/deployments"),
    v1("ces.projects.locations.apps.deployments.message.send", "POST", "v1/{+tenant}/message:send"),
    v1("ces.projects.locations.apps.deployments.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.examples.create", "POST", "v1/{+parent}/examples"),
    v1("ces.projects.locations.apps.examples.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.examples.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.examples.list", "GET", "v1/{+parent}/examples"),
    v1("ces.projects.locations.apps.examples.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.executeTool", "POST", "v1/{+parent}:executeTool"),
    v1("ces.projects.locations.apps.exportApp", "POST", "v1/{+name}:exportApp"),
    v1("ces.projects.locations.apps.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.getExtendedAgentCard", "GET", "v1/{+tenant}/extendedAgentCard"),
    v1("ces.projects.locations.apps.guardrails.create", "POST", "v1/{+parent}/guardrails"),
    v1("ces.projects.locations.apps.guardrails.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.guardrails.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.guardrails.list", "GET", "v1/{+parent}/guardrails"),
    v1("ces.projects.locations.apps.guardrails.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.importApp", "POST", "v1/{+parent}/apps:importApp"),
    v1("ces.projects.locations.apps.list", "GET", "v1/{+parent}/apps"),
    v1("ces.projects.locations.apps.message.send", "POST", "v1/{+tenant}/message:send"),
    v1("ces.projects.locations.apps.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.retrieveToolSchema", "POST", "v1/{+parent}:retrieveToolSchema"),
    v1("ces.projects.locations.apps.sessions.generateChatToken", "POST", "v1/{+name}:generateChatToken"),
    v1("ces.projects.locations.apps.sessions.runSession", "POST", "v1/{+session}:runSession"),
    v1("ces.projects.locations.apps.sessions.streamRunSession", "POST", "v1/{+session}:streamRunSession"),
    v1("ces.projects.locations.apps.tools.create", "POST", "v1/{+parent}/tools"),
    v1("ces.projects.locations.apps.tools.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.tools.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.tools.list", "GET", "v1/{+parent}/tools"),
    v1("ces.projects.locations.apps.tools.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.toolsets.create", "POST", "v1/{+parent}/toolsets"),
    v1("ces.projects.locations.apps.toolsets.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.toolsets.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.toolsets.list", "GET", "v1/{+parent}/toolsets"),
    v1("ces.projects.locations.apps.toolsets.patch", "PATCH", "v1/{+name}"),
    v1("ces.projects.locations.apps.toolsets.retrieveTools", "POST", "v1/{+toolset}:retrieveTools"),
    v1("ces.projects.locations.apps.versions.create", "POST", "v1/{+parent}/versions"),
    v1("ces.projects.locations.apps.versions.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.apps.versions.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.apps.versions.getExtendedAgentCard", "GET", "v1/{+tenant}/extendedAgentCard"),
    v1("ces.projects.locations.apps.versions.list", "GET", "v1/{+parent}/versions"),
    v1("ces.projects.locations.apps.versions.message.send", "POST", "v1/{+tenant}/message:send"),
    v1("ces.projects.locations.apps.versions.restore", "POST", "v1/{+name}:restore"),
    v1("ces.projects.locations.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.list", "GET", "v1/{+name}/locations"),
    v1("ces.projects.locations.operations.cancel", "POST", "v1/{+name}:cancel"),
    v1("ces.projects.locations.operations.delete", "DELETE", "v1/{+name}"),
    v1("ces.projects.locations.operations.get", "GET", "v1/{+name}"),
    v1("ces.projects.locations.operations.list", "GET", "v1/{+name}/operations"),
    // ---- v1beta (104 methods) ----
    beta("ces.projects.locations.apps.agents.create", "POST", "v1beta/{+parent}/agents"),
    beta("ces.projects.locations.apps.agents.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.agents.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.agents.list", "GET", "v1beta/{+parent}/agents"),
    beta("ces.projects.locations.apps.agents.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.changelogs.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.changelogs.list", "GET", "v1beta/{+parent}/changelogs"),
    beta("ces.projects.locations.apps.conversations.batchDelete", "POST", "v1beta/{+parent}/conversations:batchDelete"),
    beta("ces.projects.locations.apps.conversations.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.conversations.generateEvaluation", "POST", "v1beta/{+conversation}:generateEvaluation"),
    beta("ces.projects.locations.apps.conversations.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.conversations.list", "GET", "v1beta/{+parent}/conversations"),
    beta("ces.projects.locations.apps.create", "POST", "v1beta/{+parent}/apps"),
    beta("ces.projects.locations.apps.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.deployments.create", "POST", "v1beta/{+parent}/deployments"),
    beta("ces.projects.locations.apps.deployments.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.deployments.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.deployments.getExtendedAgentCard", "GET", "v1beta/{+tenant}/extendedAgentCard"),
    beta("ces.projects.locations.apps.deployments.list", "GET", "v1beta/{+parent}/deployments"),
    beta("ces.projects.locations.apps.deployments.message.send", "POST", "v1beta/{+tenant}/message:send"),
    beta("ces.projects.locations.apps.deployments.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationDatasets.create", "POST", "v1beta/{+parent}/evaluationDatasets"),
    beta("ces.projects.locations.apps.evaluationDatasets.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationDatasets.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationDatasets.list", "GET", "v1beta/{+parent}/evaluationDatasets"),
    beta("ces.projects.locations.apps.evaluationDatasets.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationExpectations.create", "POST", "v1beta/{+parent}/evaluationExpectations"),
    beta("ces.projects.locations.apps.evaluationExpectations.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationExpectations.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationExpectations.list", "GET", "v1beta/{+parent}/evaluationExpectations"),
    beta("ces.projects.locations.apps.evaluationExpectations.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationRuns.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationRuns.export", "POST", "v1beta/{+parent}/evaluationRuns:export"),
    beta("ces.projects.locations.apps.evaluationRuns.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluationRuns.list", "GET", "v1beta/{+parent}/evaluationRuns"),
    beta("ces.projects.locations.apps.evaluations.create", "POST", "v1beta/{+parent}/evaluations"),
    beta("ces.projects.locations.apps.evaluations.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluations.export", "POST", "v1beta/{+parent}/evaluations:export"),
    beta("ces.projects.locations.apps.evaluations.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluations.list", "GET", "v1beta/{+parent}/evaluations"),
    beta("ces.projects.locations.apps.evaluations.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluations.results.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluations.results.export", "POST", "v1beta/{+parent}/results:export"),
    beta("ces.projects.locations.apps.evaluations.results.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.evaluations.results.list", "GET", "v1beta/{+parent}/results"),
    beta("ces.projects.locations.apps.evaluations.results.runEvaluationResultMetrics", "POST", "v1beta/{+evaluationResultId}:runEvaluationResultMetrics"),
    beta("ces.projects.locations.apps.evaluations.uploadEvaluationAudio", "POST", "v1beta/{+name}:uploadEvaluationAudio"),
    beta("ces.projects.locations.apps.examples.create", "POST", "v1beta/{+parent}/examples"),
    beta("ces.projects.locations.apps.examples.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.examples.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.examples.list", "GET", "v1beta/{+parent}/examples"),
    beta("ces.projects.locations.apps.examples.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.executeTool", "POST", "v1beta/{+parent}:executeTool"),
    beta("ces.projects.locations.apps.exportApp", "POST", "v1beta/{+name}:exportApp"),
    beta("ces.projects.locations.apps.generateAppResource", "POST", "v1beta/{+parent}:generateAppResource"),
    beta("ces.projects.locations.apps.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.getExtendedAgentCard", "GET", "v1beta/{+tenant}/extendedAgentCard"),
    beta("ces.projects.locations.apps.guardrails.create", "POST", "v1beta/{+parent}/guardrails"),
    beta("ces.projects.locations.apps.guardrails.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.guardrails.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.guardrails.list", "GET", "v1beta/{+parent}/guardrails"),
    beta("ces.projects.locations.apps.guardrails.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.importApp", "POST", "v1beta/{+parent}/apps:importApp"),
    beta("ces.projects.locations.apps.importEvaluations", "POST", "v1beta/{+parent}:importEvaluations"),
    beta("ces.projects.locations.apps.list", "GET", "v1beta/{+parent}/apps"),
    beta("ces.projects.locations.apps.message.send", "POST", "v1beta/{+tenant}/message:send"),
    beta("ces.projects.locations.apps.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.retrieveToolSchema", "POST", "v1beta/{+parent}:retrieveToolSchema"),
    beta("ces.projects.locations.apps.runEvaluation", "POST", "v1beta/{+app}:runEvaluation"),
    beta("ces.projects.locations.apps.scheduledEvaluationRuns.create", "POST", "v1beta/{+parent}/scheduledEvaluationRuns"),
    beta("ces.projects.locations.apps.scheduledEvaluationRuns.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.scheduledEvaluationRuns.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.scheduledEvaluationRuns.list", "GET", "v1beta/{+parent}/scheduledEvaluationRuns"),
    beta("ces.projects.locations.apps.scheduledEvaluationRuns.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.sessions.generateChatToken", "POST", "v1beta/{+name}:generateChatToken"),
    beta("ces.projects.locations.apps.sessions.runSession", "POST", "v1beta/{+session}:runSession"),
    beta("ces.projects.locations.apps.sessions.streamRunSession", "POST", "v1beta/{+session}:streamRunSession"),
    beta("ces.projects.locations.apps.testPersonaVoice", "POST", "v1beta/{+app}:testPersonaVoice"),
    beta("ces.projects.locations.apps.tools.create", "POST", "v1beta/{+parent}/tools"),
    beta("ces.projects.locations.apps.tools.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.tools.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.tools.list", "GET", "v1beta/{+parent}/tools"),
    beta("ces.projects.locations.apps.tools.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.toolsets.create", "POST", "v1beta/{+parent}/toolsets"),
    beta("ces.projects.locations.apps.toolsets.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.toolsets.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.toolsets.list", "GET", "v1beta/{+parent}/toolsets"),
    beta("ces.projects.locations.apps.toolsets.patch", "PATCH", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.toolsets.retrieveTools", "POST", "v1beta/{+toolset}:retrieveTools"),
    beta("ces.projects.locations.apps.versions.create", "POST", "v1beta/{+parent}/versions"),
    beta("ces.projects.locations.apps.versions.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.versions.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.apps.versions.getExtendedAgentCard", "GET", "v1beta/{+tenant}/extendedAgentCard"),
    beta("ces.projects.locations.apps.versions.list", "GET", "v1beta/{+parent}/versions"),
    beta("ces.projects.locations.apps.versions.message.send", "POST", "v1beta/{+tenant}/message:send"),
    beta("ces.projects.locations.apps.versions.restore", "POST", "v1beta/{+name}:restore"),
    beta("ces.projects.locations.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.getSecuritySettings", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.list", "GET", "v1beta/{+name}/locations"),
    beta("ces.projects.locations.operations.cancel", "POST", "v1beta/{+name}:cancel"),
    beta("ces.projects.locations.operations.delete", "DELETE", "v1beta/{+name}"),
    beta("ces.projects.locations.operations.get", "GET", "v1beta/{+name}"),
    beta("ces.projects.locations.operations.list", "GET", "v1beta/{+name}/operations"),
    beta("ces.projects.locations.updateSecuritySettings", "PATCH", "v1beta/{+name}"),
];
