#!/usr/bin/env python3
"""Fetch, canonicalize, and pin the CES discovery documents.

Run by hand or in CI. Nothing at build time touches the network.
"""
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

SOURCES = [
    ("v1", "https://ces.googleapis.com/$discovery/rest?version=v1"),
    ("v1beta", "https://ces.googleapis.com/$discovery/rest?version=v1beta"),
]

REFERENCE_DIR = Path(__file__).resolve().parents[1] / "reference" / "ces"


def canonicalize(obj):
    """Serialize deterministically so the sha256 is reproducible across fetches."""
    return json.dumps(obj, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def pinned_toml(entries):
    lines = [
        "# Generated by tools/refresh_reference.py. Do not edit by hand.",
        "",
    ]
    for e in entries:
        lines += [
            "[[reference]]",
            f'version = "{e["version"]}"',
            f'url = "{e["url"]}"',
            f'revision = "{e["revision"]}"',
            f'sha256 = "{e["sha256"]}"',
            "",
        ]
    return "\n".join(lines)


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def main(argv):
    check_only = "--check" in argv
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    drifted = []
    for version, url in SOURCES:
        doc = fetch(url)
        text = canonicalize(doc)
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        path = REFERENCE_DIR / f"{version}.discovery.json"
        if check_only:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing != text:
                drifted.append(version)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
        entries.append({
            "version": version,
            "url": url,
            "revision": doc.get("revision", "unknown"),
            "sha256": digest,
        })
        print(f"{version}: revision={entries[-1]['revision']} sha256={digest[:12]} bytes={len(text)}")

    if check_only:
        if drifted:
            print(f"DRIFT: {', '.join(drifted)} differ from the vendored copies", file=sys.stderr)
            return 1
        print("no drift")
        return 0

    (REFERENCE_DIR / "PINNED.toml").write_text(pinned_toml(entries), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
