#!/usr/bin/env python3
"""Fetch, canonicalize, and pin the CES discovery documents.

Run by hand or in CI. Nothing at build time touches the network.
"""
import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

SOURCES = [
    ("v1", "https://ces.googleapis.com/$discovery/rest?version=v1"),
    ("v1beta", "https://ces.googleapis.com/$discovery/rest?version=v1beta"),
]

REFERENCE_DIR = Path(__file__).resolve().parents[1] / "reference" / "ces"

# Replicas disagree; fetch several times and keep the newest revision.
ATTEMPTS = 5


def canonicalize(obj):
    """Serialize deterministically so the sha256 is reproducible across fetches."""
    return json.dumps(obj, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def pinned_toml(entries):
    lines = [
        "# Generated by tools/refresh_reference.py. Do not edit by hand.",
        "",
    ]
    for e in entries:
        lines += [
            "[[reference]]",
            f'version = "{e["version"]}"',
            f'url = "{e["url"]}"',
            f'revision = "{e["revision"]}"',
            f'sha256 = "{e["sha256"]}"',
            "",
        ]
    return "\n".join(lines)


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def newest(docs):
    """Pick the document with the highest `revision`.

    The discovery endpoint is served from replicas that can disagree: fetching
    `?version=v1` repeatedly returns revision 20260730 and 20260806 in no stable
    order. Comparing a single fetch byte-for-byte therefore flaps. Taking the
    highest revision across several fetches converges deterministically on the
    most current surface.
    """
    if not docs:
        raise ValueError("no documents fetched")
    return max(docs, key=lambda d: str(d.get("revision", "")))


def fetch_best(url, attempts=ATTEMPTS):
    """Fetch `attempts` times and keep the most current revision seen."""
    docs = []
    errors = []
    for _ in range(attempts):
        try:
            docs.append(fetch(url))
        except Exception as exc:  # network flake on one replica must not abort
            errors.append(str(exc))
    if not docs:
        raise RuntimeError(f"all {attempts} fetches of {url} failed: {'; '.join(errors)}")
    return newest(docs)


def read_pinned_revisions(path):
    """Parse `PINNED.toml` into {version: revision} without a TOML dependency."""
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    out = {}
    for block in text.split("[[reference]]")[1:]:
        version = re.search(r'version\s*=\s*"([^"]+)"', block)
        revision = re.search(r'revision\s*=\s*"([^"]+)"', block)
        if version and revision:
            out[version.group(1)] = revision.group(1)
    return out


def main(argv):
    check_only = "--check" in argv
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    drifted = []
    pinned_revisions = read_pinned_revisions(REFERENCE_DIR / "PINNED.toml")
    for version, url in SOURCES:
        doc = fetch_best(url)
        text = canonicalize(doc)
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        path = REFERENCE_DIR / f"{version}.discovery.json"
        if check_only:
            pinned_rev = pinned_revisions.get(version, "")
            fetched_rev = doc.get("revision", "")
            if fetched_rev > pinned_rev:
                # Upstream published something newer than what we vendored.
                drifted.append(f"{version} ({pinned_rev} -> {fetched_rev})")
            elif fetched_rev == pinned_rev:
                # Same revision must mean same bytes; anything else is a
                # silent content change worth reviewing.
                existing = path.read_text(encoding="utf-8") if path.exists() else ""
                if existing != text:
                    drifted.append(f"{version} (content changed at {fetched_rev})")
            # fetched_rev < pinned_rev is replica skew: we already hold newer.
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
        entries.append({
            "version": version,
            "url": url,
            "revision": doc.get("revision", "unknown"),
            "sha256": digest,
        })
        print(f"{version}: revision={entries[-1]['revision']} sha256={digest[:12]} bytes={len(text)}")

    if check_only:
        if drifted:
            print(f"DRIFT: {', '.join(drifted)} differ from the vendored copies", file=sys.stderr)
            return 1
        print("no drift")
        return 0

    (REFERENCE_DIR / "PINNED.toml").write_text(pinned_toml(entries), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
